project: 
  type: website
  output-dir: docs

website:
  title: "Ian Blad | HR Analytics Consultant"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/007Ian/Ians_Work.git

  page-footer: 
    border: true
    left: "© 2026 Ian Blad. All rights reserved."
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ianblad
      - icon: github
        href: https://github.com/007Ian

  navbar:
    background: dark
    search: true   
    left:
      - text: "Home"
        file: index.qmd
      - text: "New Leaf Services"
        file: services.qmd        
      - text: "About"
        file: about.qmd
      - text: "Resume"
        file: resume.qmd

      - text: "Projects Portfolio"
        menu:

          - text: "Streamlining Data"
            file: Streamlining_Data/streamlining_data.qmd

          - text: "Organizational Analysis"
            file: Organizational_Analysis/Consulting_Project.qmd

          - text: "Agentic AI Course"
            file: Agentic_AI_Course/agentic_ai.qmd


    right:
      - text: "Contact"
        file: contact.qmd
format:  
  html:
    theme: 
      light: flatly
      dark: darkly
    default-theme: dark
    default-image-extension: png
    css: styles.css
    toc: true