---
title: "About Me"
subtitle: "Bridging the gap between Human Resources and Advanced Analytics"
---

## Transforming The Workplace through Data-Driven Solutions

Every since I read the book 7 Habits of Highly effective people in High School, I have been fascinated in how our ideas and perceptions about the world can activly influence the way we experience it. I think its essential to be a well read person in order to be a creative and empathetic problem solver. 

Here are some of the books/papers that have had the biggest influence on my thinking and approach to work:

**I/O Psychology:**

- **7 Habits of Highly Effective People** by Stephen Covey

- **The Best Place to Work** by Ron Friedman

- **The Culture Code** by Daniel Coyle

- **Drive** by Daniel Pink

- **Locke and Latham's Goal Setting Theory/Other Papers** by Edwin Locke and Gary Latham

- **Five Dysfunctions of a Team** by Patrick Lencioni



**Pscyhology:**

- **Thinking, Fast and Slow** by Daniel Kahneman

- **Noise** by Daniel Kahneman, Olivier Sibony, and Cass Sunstein

- **The Memory Illusion** by Elizabeth Loftus

- **False Positives in Psychology** by Uri Simonsohn, Leif Nelson, and Joseph Simmons

- **Maps of Meaning** by Jordan Peterson

- **The Sacred and the Profane** by Mircea Eliade

- **12 Rules for Life** by Jordan Peterson


**Philosophy:**

- **Famine, Affluence, and Morality** by Peter Singer

- **Argumnent from Queerness** by J.L. Mackie

- **What is Weird about Moral Deference** by Magrath

- **Evil and Omnipotence** by J.L. Mackie

- **The Free Will Defense** by Alvin Plantinga

- **Soul Making Theodicy** by John Hick

- **Horrendus Evils and God's Goodness** by Marilyn McCord Adams




[View My Projects](Organizational_Analysis/Consulting_project.qmd) | [Let's Work Together](contact.qmd)