---
layout: cv
title: Ian Blad
---
# Ian Blad
4698738496

<div id="webaddress">
<a href="ianblad@gmail.com">ianblad@gmail.com</a>
| <a href="www.linkedin.com/in/ianblad">www.linkedin.com/in/ianblad</a>
</div>


## Education

#### B.S. Psychology, Industrial/Organizational Emphasis, DS Minor	September 2021 - Present

 Brigham Young University - Idaho	Rexburg, Idaho

•	Gained foundational knowledge in organizational behavior, and personnel selection
•	Conducted multiple extensive literature reviews in belonging, retention, the OCEAN personality model and cognitive dissonance.
•	Developed strong research skills through coursework in statistics, experimental design, and data analysis forming Data Science Minor and a Statistics Certificate
•	Mastered skills in Statistical analysis, R, Python, SQL, Microsoft Excel, PowerPoint, Word and GitHub




## Professional Experience

### HR Analyst Internship	May 2025 - August 2025

HydroMax USA	Flower Mound, Texas
•	Created an automated employee evaluation system projected to save hundreds of management hours yearly
•	Executed multiple analysis in employee turnover, recruiter effectiveness and industry standards in HR metrics using R and Python tools

### Full-Time Volunteer Leader	August 2021 - August 2023

Church Of Jesus Christ of Latter-day Saints	Scotland / Ireland
•	Trained several teams sized from 8-30 people every few months
•	Gave presentations and taught skills weekly, and promoted well-being in various leadership positions


## Key Projects

### MILB Promotion Analysis	September 2025 - Present
BYUI Data Science Society	Rexburg, Idaho
•	Created a web scraper to retrieve data on MILB games relevant to attendance and promotions
•	Utilized statistical tools such as ANOVA testing and multiple adjustments to gain insights predicted to dramatically increase attendance
 
### AI Automated Septic Design Tool	August 2025 - Present
Entrepreneurial	Rexburg, Idaho
•	Designing agentic AI and web scraper, will automate job of a drafter in septic design process
•	Aiming to reduce a 7 hour work process to a 30 minute process
 
### Belonging Project for BYUI	September 2024 - November 2024
Brigham Young University Idaho	Rexburg, Idaho
•	Conducted literature review with faculty members on student belonging / retention
•	Findings will support a university-wide initiative to improve inclusion and engagement





<!-- ### Footer

Last updated: May 2013 -->